version: "3.8"

services:
  backend:
    build: ./backend
    container_name: silkflow-backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/data:/app/data  # чтобы users/orgs сохранялись между перезапусками

  web:
    build: ./web
    container_name: silkflow-web
    ports:
      - "5173:5173"
    depends_on:
      - backend